### ISSUE TITLE
[bug]: rust 产物里包含源代码绝对地址，有隐私泄露风险

### ISSUE THREAD

**Issue by xusd320** [umijs/mako#1169]
问题：
```bash
cargo build --release
open target/release/libmako.rlib
```

<img width="1920" alt="image" src="https://github.com/umijs/mako/assets/16577489/9d8c913c-824b-4efb-9064-b263fca68895">

原因：
tracing::debug 和 panic 宏展开信息会包含源代码绝对地址

解法：
依赖 rust rfc: https://rust-lang.github.io/rfcs/3127-trim-paths.html, 目前还没稳定

**Comment by Boshen** [comment]
Please switch to releasing from GitHub and enable npm provenance, this is still a security risk because you are releasing binaries.

**Comment by sorrycc** [comment]
Switched to using Github to build binaries.
