### ISSUE TITLE
Better change Rust nightly to stable

### ISSUE THREAD

**Issue by Boshen** [umijs/mako#1326]
https://github.com/umijs/mako/blob/12b685b6cd735e1a2c9d7cacc4579ed9e450c141/rust-toolchain.toml#L3

This hasn't been updated for 8 months, and nightly features are accumulating technical debt that you will regret sooner or later because upgrading rustc will become tremendously hard, and you'll miss out all the nice LLVM optimizations from recent upgrades.

**Comment by xusd320** [comment]
> https://github.com/umijs/mako/blob/12b685b6cd735e1a2c9d7cacc4579ed9e450c141/rust-toolchain.toml#L3
> 
> This hasn't been updated for 8 months, and nightly features are accumulating technical debt that you will regret sooner or later because upgrading rustc will become tremendously hard, and you'll miss out all the nice LLVM optimizations from recent upgrades.

Thanks,  we  are using a bit low version of swc, which depents on "#![feature(box_patterns)]" of nightly rust，so before change to stable rust, we must upgrade the swc version，that will be a big challenge.

**Comment by xusd320** [comment]
Ref: https://github.com/swc-project/swc/issues/8316

**Comment by Boshen** [comment]
Close as unactionable at the moment.
