### ISSUE TITLE
【特性】__webpack_public_path__ 替代方案

### ISSUE THREAD

**Issue by shockw4ver** [umijs/mako#1328]
在使用 qiankun 对应用进行 slave 化时，需进行如下配置：

```typescript
/**
   * 处理微应用静态资源的路径问题
   * @link https://qiankun.umijs.org/zh/faq#a-%E4%BD%BF%E7%94%A8-webpack-%E8%BF%90%E8%A1%8C%E6%97%B6-publicpath-%E9%85%8D%E7%BD%AE
   */
  // @ts-ignore
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
```

启用 mako 后，运行时抛出异常：

![CleanShot 2024-06-28 at 12 01 40](https://github.com/umijs/mako/assets/17818522/584c4b2b-ef4a-4d70-89ca-457bf35de1ab)

请问下 mako 侧目前有对 __webpack_public_path__ 的替代方案吗

**Comment by stormslowly** [comment]
如果是在 umi 中使用的话，可以尝试先用 runtimePublicPath 来绕过看看

**Comment by gaoxianglyx** [comment]
同问，请问解决了吗？

**Comment by gaoxianglyx** [comment]
> 如果是在 umi 中使用的话，可以尝试先用 runtimePublicPath 来绕过看看

请教下，具体怎么配置 @stormslowly

**Comment by stormslowly** [comment]
https://umijs.org/docs/api/config#runtimepublicpath

在 umi.js 加载之前 设置好  window.publicPath  即可，具体方案就你的构建流程了。

**Comment by gaoxianglyx** [comment]
> https://umijs.org/docs/api/config#runtimepublicpath
> 
> 在 umi.js 加载之前 设置好 window.publicPath 即可，具体方案就你的构建流程了。
谢谢
我尝试了在headScript，以及在入口ts里面设置window.publicPath
都不起作用。
你这边测试是可行的吗
