### ISSUE TITLE
react模板缺tsconfig

### ISSUE THREAD

**Issue by programmer-yang** [umijs/mako#1333]
跟[教程](https://makojs.dev/zh-CN/docs/getting-started#%E4%B8%8E-react-%E6%89%93%E5%8C%85)走，初始化的模板项目IDE会有ts相关的报错，只是报错，不影响运行，看是否要加tsconfig文件
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "jsx": "react",
  }
}

```

**Comment by stormslowly** [comment]
https://github.com/umijs/mako/tree/master/packages/create-mako/templates/react

可以提一个改进的 PR

**Comment by sorrycc** [comment]
Closed via https://github.com/umijs/mako/pull/1345
