### ISSUE TITLE
css is not working in the `npm create mako` template

### ISSUE THREAD

**Issue by Boshen** [umijs/mako#1338]
<img width="637" alt="image" src="https://github.com/umijs/mako/assets/1430279/069b51ec-b2d5-4166-83aa-1d1a15245655">

<img width="604" alt="image" src="https://github.com/umijs/mako/assets/1430279/94dc20dd-109f-474a-a93d-dee9920dbf58">

The title should be red right?

**Comment by stormslowly** [comment]
Mako doesn’t  have a html  plugin now,
We need to add a link for the entry css file in the
Index.html to workaround
