### ISSUE TITLE
unexpected env replace behavior

### ISSUE THREAD

**Issue by kagawagao** [umijs/mako#1344]
https://github.com/umijs/mako/blob/2fa13fba3cc2337cb9f4e485d6625e98fa585713/crates/mako/src/visitors/env_replacer.rs#L119-L122

the default replacer broked some case which used to transform compile environment varibale as runtime config, maybe we should not replace these not defined variables with `undefined`, or provide a config item to change this behavior.

**Comment by sorrycc** [comment]
I've tested webpack and rspack, although the outputed code is different, but the result is all `undefined`.

**Comment by kagawagao** [comment]
I've find a way to solve this problem
