### ISSUE TITLE
[discuss]dependence loop detecting as a feature

### ISSUE THREAD

**Issue by stormslowly** [umijs/mako#1359]
有些项目会有循环依赖，某些循环依赖会在运行时报错。
比如在循环依赖上的一个模块导出变量来自一个 let/const 定义的变量，那么就有可能触发 `access before  initialize` 的错误。
或者是一个 var 定义的变量，提升后，因为循环依赖访问时机不同，可能取到 undefined 值。

## 解法

mako 可以利用现在的拓扑排序的结果，检测是项目中的所有环，通过配置决定如果是纯项目形成的环就报错。

> 循环依赖虽然没有错，但是如果没有会更好。

**Comment by fengmk2** [comment]
nodejs require 下出现这种循环依赖，第二个依赖会返回空

**Comment by stormslowly** [comment]
嗯 esm 和 cjs 还有点区别的， esm 里面的 import 相当于一个指向最新值的引用，所以可能会出现一个模块里面 undefined ，另外一个又有了，这种情况就容易蒙。

**Comment by xierenyuan** [comment]
+1 我们以遇到了同样的问题
