### ISSUE TITLE
Issue when trying to build with Mako in existing Ant Design project

### ISSUE THREAD

**Issue by patkepa** [umijs/mako#1362]
Hello!

I wanted to check out Mako while building an existing big projects that was written using Ant Design 5 Framework.
After going to directory, having installed Mako, and typing `npx mako build`
I receive the error below:

```bash
  webpack loader syntax is not supported, since found dep "file-loader?esModule=false!./src-noconflict/ext-beautify.js" in "/Users/pat/IdeaProjects/enterprise-project/modules/ui/node_modules/ace-builds/webpack-resolver.js"] {
    code: 'GenericFailure'
}

````
How could I go with this? Its inside of a dependency inside of my project, is there some way to fix this issue?

**Comment by stormslowly** [comment]
could you plz provide a minimal reproduce repo.

and in my guess,  Mako uses `src/index.ts[x]` as the default entry of the project,  in your project src/index.ts maybe a build related config file that will require ace-build. 
try create a `mako.config.json` at the root of your project, with below content, and build agian

```json
{
  "entry":{
    "index": "the relative path to the real entry file of the project"
  }
}
```

**Comment by sorrycc** [comment]
don't use `webpack-resolver.js`, use [`esm-resolver.js`](https://github.com/ajaxorg/ace-builds/blob/master/esm-resolver.js) instead.
