### ISSUE TITLE
anlayze 功能启用不生效

### ISSUE THREAD

**Issue by xierenyuan** [umijs/mako#1364]
<img width="1073" alt="image" src="https://github.com/umijs/mako/assets/7599351/18db8271-7aac-43ea-9584-c81a7e792bf4">
umirc.ts 配置 analyze 后 执行无法使用 analyze 功能

**Comment by LovePlayCode** [comment]
有仓库地址吗 我看看

**Comment by xierenyuan** [comment]
> 有仓库地址吗 我看看

umi-mako-demo 2.zip

**Comment by sorrycc** [comment]
@LovePlayCode bundler-mako 层没对上，小问题。
