### ISSUE TITLE
cargo install cargo-binstall 老是报版本的错误

### ISSUE THREAD

**Issue by Dan-0216** [umijs/mako#1379]
执行安装的时候报了这个错误
![image](https://github.com/umijs/mako/assets/27200655/478dc9ff-b363-4b4a-9d5b-81a816c4c007)

感觉像是在rust-toolchain.toml 指定了版本号导致，更改以后重新安装就好了
![image](https://github.com/umijs/mako/assets/27200655/6fe63c52-f751-4770-9e8e-bc31ff542285)

**Comment by stormslowly** [comment]
可能镜像源的问题 or 网络问题
自行解决吧
