### ISSUE TITLE
bug: cannot use dot accessor in define

### ISSUE THREAD

**Issue by PeachScript** [umijs/mako#1382]
比如存在以下 define 值：

```json
{
  "define": {
    "process.env": { "a": 1 },
    "process.env.b": 2
  }
}
```

以及在代码中这么写：

```ts
console.log(process.env.a);
console.log(process.env.b);
```

在 Mako 中会输出两个 `undefined`，而在 Webpack 中会输出 `1` 和 `2`，Mako 不支持配置 `x.y` 的 key，需要改成和社区共识保持一致，需要如下改动：

1. 支持 `x.y` 的形式
2. 如果 `x.y` 是对象值且不含 `z`，需要支持替换单独定义的 `x.y.z` 值

另外还有个行为比较诡异，当配置如下 define 值：

```json
{
  "define": {
    "xxx": 1
  }
}
```

在代码里无论是写 `xxx` 还是 `process.env.xxx` 都会被 Mako 替换，Webpack 没有这个特殊行为

**Comment by drizzlesconsin** [comment]
怪不得 `process.env.PUBLIC_PATH` 丢了

**Comment by stormslowly** [comment]
⾺~

**Comment by stormslowly** [comment]
🐴🐴🐴
