### ISSUE TITLE
RFC：Mako 特有配置在 umi 下的使用

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#1389]
## 背景

比如 px2rem、experimental.webpackSyntaxValidate、flexBugs、moduleIdStrategy、optimization 等，这些目前要使用是需要新增一个 mako.config.json 的，这对于 Umi 用户来说并不友好。

## 方案

Umi 的 mako 配置目前是空对象 `{}`，如果用户在这里有配置属性，则通过白名单的方式（允许部分，有些试验性的就先不暴露了，避免 Umi 层的 break change），把配置透传给 mako。

e.g.

```ts
// .umirc.ts
export default {
  mako: { px2rem: {} }
}
```

**Comment by xiaohuoni** [comment]
怎么确定白名单？现在用到以下几个，还有什么需要的吗？
```ts
const supportMakoConfigKeys = [
    'px2rem',
    'experimental',
    'flexBugs',
    'moduleIdStrategy',
    'optimization',
  ];
```

**Comment by sorrycc** [comment]
@xiaohuoni 差不多就这些吧。

**Comment by stormslowly** [comment]
'moduleIdStrategy',  不要把容易配置不当产物体积变大 ，然后来答疑 
这个使用的场景也是我们 debug 的时候用

**Comment by xiaohuoni** [comment]
那我先去掉

**Comment by sorrycc** [comment]
已支持。
