### ISSUE TITLE
添加mako失败

### ISSUE THREAD

**Issue by cjdxhjj** [umijs/mako#1395]
![image](https://github.com/umijs/mako/assets/5616997/320cccbe-17a9-4239-8920-6639cf1738e9)
手工添加mako配置节以启用mako
![image](https://github.com/umijs/mako/assets/5616997/97cac3bf-c884-4caf-9dd0-5a42451f3a05)
编译时mako未启用
![image](https://github.com/umijs/mako/assets/5616997/c724e797-4fd6-4537-948e-e944ca9fb915)

**Comment by cjdxhjj** [comment]
![aaxss](https://github.com/umijs/mako/assets/5616997/53c94826-a029-4354-a70e-2b76724730be)

**Comment by cjdxhjj** [comment]
[umi.log](https://github.com/user-attachments/files/16159094/umi.log)

**Comment by cjdxhjj** [comment]
上图是我用umi新创建的项目，添加mako失败

**Comment by cjdxhjj** [comment]
新项目手工加上mako配置启用也无效
![image](https://github.com/umijs/mako/assets/5616997/32a9fdc2-7ab9-4fb6-9915-5398166394d0)
![image](https://github.com/umijs/mako/assets/5616997/ec78377d-5988-429b-acad-fd7613f72dc8)

**Comment by stormslowly** [comment]
目前 mako 还不支持 windows   #1343 

你的 set 命令失败可能是 windows 上需要 `umi config set '{}'` ( 没有 window 瞎猜的
