### ISSUE TITLE
关于Windows环境支持

### ISSUE THREAD

**Issue by phoema** [umijs/mako#1396]
我在UMI4.3.0中开启配置mako，编译仍然使用的webpack，查询FAQ提及
Does Mako Support Windows?
Not yet. Mako is currently only supported on MacOS and Linux. Windows support is planned after the open-source release.

请问有对windows支持的时间点吗？

**Comment by sorrycc** [comment]
Duplicated, 在 #1343 跟进进展，暂无明确时间点，已加 TODO，应该不会很久。
