### ISSUE TITLE
Feat:  插件处理的内容应该继续往后执行

### ISSUE THREAD

**Issue by xierenyuan** [umijs/mako#1403]
<img width="802" alt="image" src="https://github.com/umijs/mako/assets/7599351/4c41d584-f810-479f-8345-69cb62777676">

自定义 entry 后通过 mako 插件 处理 tsx 内容 会导致热更新失效

**Comment by stormslowly** [comment]
yes, it should be processed in a pipeline

**Comment by sorrycc** [comment]
entry 的逻辑是这样，

1、在 dev + hmr 模式下，会给 entry 加 `?hmr` 后缀，比如 index.ts 会变成 `index.ts?hmr`
2、load.rs 里会处理 `?hmr` 后缀的文件，然后带上 hmr 相关 runtime，让 hmr 生效

虽然用户配的 load hook 在前，但**只要不处理 ?hmr** 的场景，应该是不会有问题的。

**Comment by xierenyuan** [comment]
[umi-mako-demo 4.zip](https://github.com/user-attachments/files/16330082/umi-mako-demo.4.zip) 最小复现
如果入口文件经过了插件处理 会导致热更新失效

**Comment by sorrycc** [comment]
试过在自定义 load 里加一段这个就好了。

```ts
if (filePath.includes('?hmr')) {
  return;
}
```
