### ISSUE TITLE
mako 结合 tailwindcss 使用时无法识别配置的路径

### ISSUE THREAD

**Issue by dongjb** [umijs/mako#1423]
### 现象说明

1. 我在.env文件中配置了环境变化，用来设置 publicPath
![CleanShot 2024-07-18 at 10 56 23@2x](https://github.com/user-attachments/assets/a0f3567e-6f99-430d-a180-6f6e08cd1a05)

2. 我在tailwind.config.js中使用了这个环境变量 process.env.PUBLIC_PATH用来设置背景图路径，并且我确保我的 public 目录下是有这两个文件的
![CleanShot 2024-07-18 at 10 58 05@2x](https://github.com/user-attachments/assets/905f1bf0-322f-46be-9d52-23dca701590f)

### 结果展示
在启动时报错无法解决图片路径

![CleanShot 2024-07-18 at 11 00 10@2x](https://github.com/user-attachments/assets/c14d7c35-df4d-4aac-9fb1-7cde05aaee8a)

### 期望结果

期望无报错，能正确识别路径

**Comment by yurnery** [comment]
tailwind还需要什么配置吗? 我从 umi 直接切过来, 原来的extraPostCSSPlugins不支持, 不知道怎么弄了

**Comment by dongjb** [comment]
> tailwind还需要什么配置吗? 我从 umi 直接切过来, 原来的extraPostCSSPlugins不支持, 不知道怎么弄了

我这里没有配置啥 tailwind，我只是用来继承增加主题配置

**Comment by sorrycc** [comment]
@dongjb 给个最简复现？

**Comment by dongjb** [comment]
> @dongjb 给个最简复现？

```
npx create-umi@latest
? Pick Umi App Template › - Use arrow-keys. Return to submit.
    Simple App
❯   Ant Design Pro
    Vue Simple App
```
    
`max g tailwindcss`

```
module.exports = {
  content: [
    './src/pages/**/*.tsx',
    './src/components/**/*.tsx',
    './src/layouts/**/*.tsx',
    './src/loading.tsx',
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      backgroundImage: {
        'license-bg': `url('/business-license.webp')`,
      },
    },
  },
};

``` 

在 public 目录添加business-license.webp图片，能稳定复现这个错误，不过它只是提示错误，并不影响最终呈现效果
![CleanShot 2024-07-18 at 14 41 22@2x](https://github.com/user-attachments/assets/29db91b7-2daf-4af3-96aa-65fba38db063)

**Comment by stormslowly** [comment]
duplicated with #314

**Comment by stormslowly** [comment]
duplicated https://github.com/umijs/mako/issues/1382

**Comment by Nice-PLQ** [comment]
> tailwind还需要什么配置吗? 我从 umi 直接切过来, 原来的extraPostCSSPlugins不支持, 不知道怎么弄了

同样遇到这个问题，mako不支持postcss的话，umi4如何支持tailwind呢？

**Comment by HuemengHm** [comment]
> > tailwind还需要什么配置吗? 我从 umi 直接切过来, 原来的extraPostCSSPlugins不支持, 不知道怎么弄了
> 
> 同样遇到这个问题，mako不支持postcss的话，umi4如何支持tailwind呢？

+1 问下

**Comment by wolmhp** [comment]
> > tailwind还需要什么配置吗? 我从 umi 直接切过来, 原来的extraPostCSSPlugins不支持, 不知道怎么弄了
> 
> 同样遇到这个问题，mako不支持postcss的话，umi4如何支持tailwind呢？

+1 同问
