### ISSUE TITLE
less导入node_modules中的样式路径问题

### ISSUE THREAD

**Issue by jinxiangqiang** [umijs/mako#1427]
@import 'antd/dist/reset.css';
less中引用antd样式的会被解析到当前目录  ”../src/style/antd/dist/reset.css“
正确应该是“antd/dist/reset.css”

**Comment by sorrycc** [comment]
1、请给最简复现，我们有用例保证 less 里 import 模块时，加不加 `~` 都能 resolve 到依赖里的样式，见 https://github.com/umijs/mako/blob/master/e2e/fixtures/less.import-npm-deps/expect.js#L16-L17
2、可尝试加 `~` 前缀，比如 `@import '~antd/dist/reset.css';`，但理论上并不需要

**Comment by jinxiangqiang** [comment]
"@core/components": "workspace:^*"

@import '@core/components/src/style/index';
在此库less中包含@import '~antd/dist/reset.css';
导致编译时报错 NotFound("../../../packages/core_components/src/style/~antd/dist/reset.css")

**Comment by sorrycc** [comment]
请给最简复现，应该是没找到 antd 这个依赖。

**Comment by jeasonnow** [comment]
我猜测这个复现场景可能是这种场景：
1. 使用 monorepo 在 root 目录进行 install，导致公共依赖被安装到 root 层的 node_modules.
2. 进入 package 子包使用 mako 进行 build. 此时 mako 的 css resolver 的解析是会出问题的

**Comment by jeasonnow** [comment]
@jinxiangqiang 是不是在 monorepo 的仓库里使用 mako 在子包里进行打包，而不是在根目录配置 mako 进行子包的打包导致的？区别是：
```
// bad
- node_modules
- packages
   - package1
      - mako.config.json
      
// good
- node_modules
- packages
   - package1
- mako.config.json
```

本地增加 `e2e` 测试 `monorepo` 使用上面的 `good case` 是可以成功编译的.
![CleanShot 2024-07-25 at 10 55 53](https://github.com/user-attachments/assets/7b97d4c2-6374-4426-a2da-6a2dd3157a54)
![CleanShot 2024-07-25 at 10 57 00](https://github.com/user-attachments/assets/85126d94-8278-4f86-84b0-dfd892a19184)

**Comment by jinxiangqiang** [comment]
在子应用.dumi中global.less
@import ***@***.***/components/src/style/index';
@***@***.*** '~antd/dist/reset.css', ***@***.***/components，基座开启mako，报错


***@***.***/components": "workspace:^*",



在 2024-07-25 10:57:34，"santree" ***@***.***> 写道：

@jinxiangqiang 是不是在 monorepo 的仓库里使用 mako 在子包里进行打包，而不是在根目录配置 mako 进行子包的打包导致的？区别是：

// bad
- node_modules
- packages
   - package1
      - mako.config.json
      
// good
- node_modules
- packages
   - package1
- mako.config.json


本地增加 e2e 测试 monorepo 使用上面的 good case 是可以成功编译的.
CleanShot.2024-07-25.at.10.55.53.png (view on web)
CleanShot.2024-07-25.at.10.57.00.png (view on web)

**Comment by jeasonnow** [comment]
> 在子应用.dumi中global.less @import ***@***.***/components/src/style/index'; @***@***.*** '~antd/dist/reset.css', ***@***.***/components，基座开启mako，报错 ***@***.***/components": "workspace:^*", 在 2024-07-25 10:57:34，"santree" ***@***.***> 写道： @jinxiangqiang 是不是在 monorepo 的仓库里使用 mako 在子包里进行打包，而不是在根目录配置 mako 进行子包的打包导致的？区别是： // bad - node_modules - packages - package1 - mako.config.json // good - node_modules - packages - package1 - mako.config.json 本地增加 e2e 测试 monorepo 使用上面的 good case 是可以成功编译的. CleanShot.2024-07-25.at.10.55.53.png (view on web) CleanShot.2024-07-25.at.10.57.00.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

经过我的测试，我提到的 bad case 实际上也没有问题，所以我删掉了我的回复，听你的描述，你似乎是使用 qiankun 并将 dumi 作为子应用，然后开启 mako 打包？

**Comment by jinxiangqiang** [comment]
***@***.***/components": "workspace:^",作为一个dumi创建的公共组件库,样式默认在我的基座中被引用了，只要基座的umi开启mako，~antd/dist/reset.css就会导致报错
















在 2024-07-25 14:51:40，"santree" ***@***.***> 写道：

在子应用.dumi中global.less @***@***.***/components/src/style/index'; @@. '~antd/dist/reset.css', @./components，基座开启mako，报错 @./components": "workspace:^", 在 2024-07-25 10:57:34，"santree" @.> 写道： @jinxiangqiang 是不是在 monorepo 的仓库里使用 mako 在子包里进行打包，而不是在根目录配置 mako 进行子包的打包导致的？区别是： // bad - node_modules - packages - package1 - mako.config.json // good - node_modules - packages - package1 - mako.config.json 本地增加 e2e 测试 monorepo 使用上面的 good case 是可以成功编译的. CleanShot.2024-07-25.at.10.55.53.png (view on web) CleanShot.2024-07-25.at.10.57.00.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.*>

经过我的测试，我提到的 bad case 实际上也没有问题，所以我删掉了我的回复，听你的描述，你似乎是使用 qiankun 并将 dumi 作为子应用，然后开启 mako 打包？

**Comment by Promisezhangbo** [comment]
我也有同样的问题，是微前端，pnpm的 workspace 模式
|-packages
| |-- rootComponents  // 这个是微前端中得公共组件，这个是用的dumi框架，里面入口引用了 @import 'antd/dist/reset.css';
| |-- app1
| |-- app2
| |-- appRoot
|-package.json // antd 安装在根目录

app1中引用了 rootComponents 中的组件，此时run app1, 此时开启mako便会报错，关闭mako则是正常的

`
failed to resolve ../theme/~antd/dist/reset.css from /Desktop/test02/higgs-frontend/node_modules/.pnpm/@sensecore+core-components@2.0.0_@babel+core@7.25.2_@types+react@17.0.45_eslint@8.57.0_jest@2_zg5azvyohc72npheixsql4waq4/node_modules/@sensecore/core-components/dist/esm/core-container/index.less with resolver err: NotFound("../theme/~antd/dist/reset.css")
`

**Comment by sorrycc** [comment]
Will be reopened when reproduction is supplied.
