### ISSUE TITLE
开发服务器不会自动刷新

### ISSUE THREAD

**Issue by yurnery** [umijs/mako#1428]
把之前一个很大的 umi 项目转为这个打包, 
控制台会报错`Error watching files: Too many open files (os error 24) about ["xxx/packages/bair/node_modules/.../src/IconAlipayCircleFilled/index.tsx"]`, 然后就没法热更新了, 而且刷新网页请求到的也是老, 只有新启动开发服务器, 编译的结果才是正确的.

**Comment by sorrycc** [comment]
1、尝试关闭当前 terminal tab，重开能解吗？
2、这是 monorepo 项目？

**Comment by jeasonnow** [comment]
了解了一下实现，感觉可以尝试调整一下 `watch.ignorePaths` 来避免一下。但是 `mako` 是不是可以尝试在 `watch` 中增加一个多线程分片的处理，比如监听根目录下面的子目录，以及依赖图中不在根目录下的目录时，使用 `thread::spawn` 来新开线程执行？

**Comment by afc163** [comment]
antd 内 +1

**Comment by jeasonnow** [comment]
> 了解了一下实现，感觉可以尝试调整一下 `watch.ignorePaths` 来避免一下。~但是 `mako` 是不是可以尝试在 `watch` 中增加一个多线程分片的处理，比如监听根目录下面的子目录，以及依赖图中不在根目录下的目录时，使用 `thread::spawn` 来新开线程执行？~
> 
> `Watcher` 只实例化一次而且没有 `clone` 能力...

https://github.com/notify-rs/notify/issues/596

参考这个，问题是因为 `mako` 在使用 `notify` 时 feature 是 `macos_kqueue` 而导致的。

`kqueue` 和 `fsevent` 具体的差别如下：

- **`kueue`**：
  - 主要用于处理通用的异步任务和事件队列。
  - 如果在文件监控的实现中使用 `kueue` 处理每个文件的事件监控，可能会导致每个文件或目录都单独打开一个文件描述符。
  - 如果监控大量文件，每个文件都可能占用一个文件描述符，从而很快达到系统的文件描述符限制。

- **`fsevent_sys`**：
  - 专门设计用于文件系统事件监控。
  - 利用操作系统提供的文件系统事件通知机制，比如 macOS 的 FSEvents 或 Linux 的 inotify。
  - 这些机制通常允许监控整个目录树而不需要为每个文件单独打开文件描述符，从而减少了文件描述符的使用。
  
  是不是可以考虑调整 `feature` 为 `macos_fsevent` 来解一下？

**Comment by yurnery** [comment]
> 1、尝试关闭当前 terminal tab，重开能解吗？ 2、这是 monorepo 项目？

1. 重新打开了很多次, 都是一样的报错;
2. 是 menorepo 项目, 引用的 antd , 报错的是 antd 里面的组件

**Comment by chaomingd** [comment]
dumi 开启 mako 也遇到了
![image](https://github.com/user-attachments/assets/98948739-d122-4f2a-913c-6d09a7a3a579)

**Comment by yurnery** [comment]
> > dumi 开启 mako 也遇到了 ![image](https://private-user-images.githubusercontent.com/31772762/354106426-98948739-d122-4f2a-913c-6d09a7a3a579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDMyODIsIm5iZiI6MTcyMjUwMjk4MiwicGF0aCI6Ii8zMTc3Mjc2Mi8zNTQxMDY0MjYtOTg5NDg3MzktZDEyMi00ZjJhLTkxM2MtNmQwOWE3YTNhNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5MDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjU5ZDBmYmE4MGEyYTdhYmY0YWJjNWE2YjdhMGIxZDg0YmZjNzNmODE0YzY5ODMwMThkOGI1MjQ0ZDc5OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pg06l0bMCtCYkzyji4iBUCSqfjWyihzQnOIsrEDPLuA)
> 
> 试试执行 `ulimit -n` 看看返回值？

ulimit -n
2560

**Comment by sorrycc** [comment]
补一下 antd 的复现步骤。

1、git clone
2、npm i
3、npm start
4、修改 markdown 文件，比如 docs/blog/build-ghost.en-US.md

然后报错。

```
Error watching files: Too many open files (os error 24)
```

**Comment by nathanlao** [comment]
> 补一下 antd 的复现步骤。
> 
> 1、git clone 2、npm i 3、npm start 4、修改 markdown 文件，比如 docs/blog/build-ghost.en-US.md
> 
> 然后报错。
> 
> ```
> Error watching files: Too many open files (os error 24)
> ```

antd 本地开发也遇到同样的问题

**Comment by Jinbao1001** [comment]
close with #1550
