### ISSUE TITLE
在  "umi": "^3.5.37",  版本使用了这个，构建后有报错了，看起来是有语法兼容性问题

### ISSUE THREAD

**Issue by markyun** [umijs/mako#1433]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/4c0badca-66f1-48f6-a21d-325a91142637">

构建后有报错了，看起来是有语法兼容性问题，具体错误如图。

```
 &:hover {
      background-color: var(--action-background, rgba(0, 0, 0, 0.05));

      svg {
        fill: #6f7b88;
      }
    }
```

**Comment by markyun** [comment]
使用的 [umi-plugin-mako](https://github.com/xiaohuoni/umi-plugin-mako)  插件

**Comment by sorrycc** [comment]
css？css 不支持嵌套的，可以改成这样。

```
 &:hover {
      background-color: var(--action-background, rgba(0, 0, 0, 0.05));
    }
 &:hover svg {
        fill: #6f7b88;
}
```

**Comment by markyun** [comment]
> css？css 不支持嵌套的，可以改成这样。
> 
> ```css
> &:hover {
>   background-color: var(--action-background, rgba(0, 0, 0, 0.05));
> }
> &:hover svg {
>   fill: #6f7b88;
> }
> ```

谢谢，解决了这个问题，不过出现了新的 error 提示。

<img width="2470" alt="image" src="https://github.com/user-attachments/assets/63578491-4616-417e-85e3-c51639db38ed">

**Comment by markyun** [comment]
> > css？css 不支持嵌套的，可以改成这样。
> > ```css
> > &:hover {
> >   background-color: var(--action-background, rgba(0, 0, 0, 0.05));
> > }
> > &:hover svg {
> >   fill: #6f7b88;
> > }
> > ```
> 
> 谢谢，解决了这个问题，不过出现了新的 error 提示。
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/2833137/350896067-63578491-4616-417e-85e3-c51639db38ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzc3MzUsIm5iZiI6MTcyMTYzNzQzNSwicGF0aCI6Ii8yODMzMTM3LzM1MDg5NjA2Ny02MzU3ODQ5MS00NjE2LTQxN2UtODVlMy1jNTE2MzlkYjM4ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDgzNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY0NGYzOWE5NTdhZmUxZDlkZTM1YTMwNjRhOTYwM2YwYjQ0YTEzMWJjNDdiMWRmNjk4NDFmZDlhMzkzZGEzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1Jquv9y-nm4B8eSvzbx-N9KBh5PgNnw6-jrlEDdaIcY">


同条件下，用 之前的配置 esbuild 是不会出错的。
https://p.ipic.vip/e4nldh.png

**Comment by sorrycc** [comment]
1、需要给复现了，从日志看不出问题。
2、 @xiaohuoni 可以关注下。

**Comment by xiaohuoni** [comment]
@sorrycc 有私聊我，沟通了
@markyun 看起来是配置了拆包，配置去掉试试，或者给个复现给我，不方便公开，复现可以私聊我

**Comment by xiaohuoni** [comment]
解决方案是去掉项目中的 chunks 配置。
原因是build 时 chunk 列表动态读的 mako 的 `stats.json`

**Comment by markyun** [comment]
> 解决方案是去掉项目中的 chunks 配置。 原因是build 时 chunk 列表动态读的 mako 的 `stats.json`

感谢 @xiaohuoni  像mako的构建速度一样，毫秒级解决了问题。

**Comment by sorrycc** [comment]
@xiaohuoni 在 umi-plugin-mako 里针对这个场景加个报错引导吧。
