### ISSUE TITLE
perf: too much module id clone

### ISSUE THREAD

**Issue by xusd320** [umijs/mako#1440]
As blow, we should not use String to represent module id
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/1b3ada99-7475-44ce-a648-b5ada91c66c8">

**Comment by shulaoda** [comment]
Maybe we can use `ArcStr` which is used by `rolldown`.

**Comment by xusd320** [comment]
No obvious improvement. See https://github.com/umijs/mako/pull/1459. The problem is about CPU, not about heap, analysis is here.
