### ISSUE TITLE
控制台报错 xxx.css because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by consistent-k** [umijs/mako#1467]
复现仓库：https://github.com/consistent-k/umi-mako/blob/main/.umirc.ts
关闭mako之后正常，开启之后报错如下

![image](https://github.com/user-attachments/assets/f022f8c5-57e0-4742-aee9-367d1727b421)

**Comment by wangsanshao** [comment]
应该是publicPath的问题，升级到最新版本会解决

**Comment by consistent-k** [comment]
> 应该是publicPath的问题，升级到最新版本会解决
升级了umimax 启动发现还有这个报错
![image](https://github.com/user-attachments/assets/692f8714-8d0b-4d7a-9ee7-e7718a64c97f)

![image](https://github.com/user-attachments/assets/b1843962-694d-4402-a55c-e52fe0c7cb69)

**Comment by consistent-k** [comment]
@whyer11 刚升级了@umijs/max到4.3.18 报错依旧存在  是umi还么有跟进新版本吗
