### ISSUE TITLE
bug: Mako integration with SassLoader causing errors in Dumi

### ISSUE THREAD

**Issue by Xy2002** [umijs/mako#1476]
## Description

When enabling both Mako and SassLoader in Dumi, the web page throws an error. It appears that Mako has poor support for Sass, preventing the project from running correctly when both are enabled.

## Steps to Reproduce

1.	Create a new Dumi project or use an existing one.
2.	Enable Mako integration within the `.dumirc.ts`. (`mako: {}`)
3.	Add and configure SassLoader in the `.dumirc.ts`. (`sassLoader: {}`)
4.	Run the Dumi project.
5.	Observe the error in the browser console or terminal.

## Reproduce Demo link

[CodeSandbox](https://codesandbox.io/p/devbox/dumi-mako-sass-qwtzvn)

**Comment by jeasonnow** [comment]
https://github.com/umijs/mako/blob/7353c9ab068884f8e2cfb67282dd697774fdb826/packages/mako/src/index.ts#L116-L136

调整你的配置可以解决这个问题。
```javascript
import { defineConfig } from 'dumi';

export default defineConfig({
  outputPath: 'docs-dist',
  themeConfig: {
    name: 'dumi-mako-sass',
  },
  mako:{
    sass: {}
  },
});
```
https://codesandbox.io/p/devbox/dumi-mako-sass-forked-7ymhqc?file=%2F.dumirc.ts%3A1%2C1-12%2C1

**Comment by Xy2002** [comment]
> https://github.com/umijs/mako/blob/7353c9ab068884f8e2cfb67282dd697774fdb826/packages/mako/src/index.ts#L116-L136
> 
> 调整你的配置可以解决这个问题。
> 
> ```js
> import { defineConfig } from 'dumi';
> 
> export default defineConfig({
>   outputPath: 'docs-dist',
>   themeConfig: {
>     name: 'dumi-mako-sass',
>   },
>   mako:{
>     sass: {}
>   },
> });
> ```
> 
> https://codesandbox.io/p/devbox/dumi-mako-sass-forked-7ymhqc?file=%2F.dumirc.ts%3A1%2C1-12%2C1

我在上面贴出的CodeSandbox以及本地项目按照这样修改了，但是仍然出现相同的问题，可以麻烦您再看看是什么问题吗🥹
