### ISSUE TITLE
在某些情况下，mako的HMR速度会比mfsu的更慢？

### ISSUE THREAD

**Issue by ShotHeadman** [umijs/mako#1481]
mako 版本为 0.7.9
在我们目前的项目中，如果使用最新版umi的 mfsu，HMR的时间大概在 1.5s  左右。
使用 mako 之后，构建时间缩短了很多，但是 HMR 的 时间反而在 5s 到 6s 之间，（Full rebuilt in 5xxx ms）
我这边做了很多配置替换，但是没有实验出来哪个配置影响了 mako 的 HMR 时长, 这是否是正常现象？

以下为配置：
```typescript
import { defineConfig } from 'umi';
import define from './defineEnv';
import proxy from './proxy';
import theme from './theme';
import qiankun from './qiankun';
import routes from '../src/routes';

export default defineConfig({
  plugins: [
    require.resolve('@umijs/plugins/dist/initial-state'),
    require.resolve('@umijs/plugins/dist/model'),
    require.resolve('@umijs/plugins/dist/qiankun'),
    require.resolve('@umijs/plugins/dist/request'),
    require.resolve('@umijs/plugins/dist/tailwindcss'),
  ],
  define,
  proxy,
  routes,
  theme,
  qiankun,
  model: {},

  mountElementId: 'root', 

  mako: {},
  initialState: { loading: '@/components/Loading' },

  externals: {
      react: 'React',
      'react-dom': 'ReactDOM',
    },
  tailwindcss: {},
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'xxx',
        libraryDirectory: 'lib',
        style: true,
      },
    ],
  ],
});
```

**Comment by PeachScript** [comment]
秒级热更肯定不正常，但需要复现仓库才能排查，看看是否能提供下复现仓库，如果是内部项目请注意脱敏

**Comment by ShotHeadman** [comment]
> 秒级热更肯定不正常，但需要复现仓库才能排查，看看是否能提供下复现仓库，如果是内部项目请注意脱敏

我花了点时间拆了项目 1/5 大小的demo出来，但是这个时候 mako 热更速度是更快的，目前只有完全体项目能复现，我还得研究一下

**Comment by sorrycc** [comment]
加 `RUST_LOG=mako=debug,info` 试下，启动、修改代码，然后把日志信息提交下。

**Comment by ShotHeadman** [comment]
> 加 `RUST_LOG=mako=debug,info` 试下，启动、修改代码，然后把日志信息提交下。

DEBUG mako::dev: watch paths detected: ["/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx"]
DEBUG mako::dev: checking update status...
Checking...
DEBUG mako::dev::update: update: [("/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx", Modify)]
DEBUG mako::dev::update: checking added...
DEBUG mako::dev::update: checking added...done, has_added:false
DEBUG mako::dev::update: filtering paths...
DEBUG mako::dev::update:   > /home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx is filtered
DEBUG mako::dev::update: filtering paths...done
DEBUG mako::dev::update: remove: []
DEBUG mako::dev::update: after build_by_remove
DEBUG mako::dev::update:   > removed_module_ids: {}
DEBUG mako::dev::update:   > affected_module_ids: {} (these will be added to modified
DEBUG mako::dev::update: modify: ["/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx"]
DEBUG mako::dev::update: build by modify: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" start
DEBUG mako::build::load: load: File { path: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx", relative_path: "src/pages/handle/menus/authRuleManager/index.tsx", extname: "tsx", content: None, is_under_node_modules: false, is_css_modules: false, is_virtual: false, is_entry: false, pathname: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx", search: "", params: [], fragment: None }
DEBUG mako::build::parse: parse js: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx"

Rebuilding...
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "react-refresh"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "react/jsx-dev-runtime"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/layout/ListPage"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./config"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/hooks/useRequestWithParams"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/pro/Table"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "antd"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./components/FormDrawer"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "custom-icons"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/services/evaluation/authentication"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/pro/SearchForm"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/pro/Form"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./components/EditorDrawer"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./util"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/constants/columnConfig"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/constants"
DEBUG mako::dev::update:   > missing deps: {}
DEBUG mako::build::parse: parse js: "virtual:external_react"
DEBUG mako::dev::update: build by modify: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" end
DEBUG mako::dev::update: after build_by_modify
DEBUG mako::dev::update:   > modified_module_ids: {ModuleId { id: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" }}
DEBUG mako::dev::update:   > add_paths: [] (these will be added to added)
DEBUG mako::dev::update: add: []
DEBUG mako::dev::update: update_result: UpdateResult { added: {}, removed: {}, modified: {ModuleId { id: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" }}, dep_changed: {ModuleId { id: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" }} }
DEBUG mako::dev: has_missing_deps: false
DEBUG mako::dev: checking update status... done
DEBUG mako::dev: update status is ok, is_updated: true
DEBUG mako::generate: generate_hot_update_chunks start
DEBUG mako::generate: hot-update:generate
DEBUG mako::generate::group_chunk: group_hot_update_chunk
DEBUG mako::generate::group_chunk: group_chunk

Done in 35ms.
DEBUG mako::generate::group_chunk: entries: [ModuleId { id: "/home/abc/test-project/src/.umi/umi.ts?hmr" }]
DEBUG mako::generate::optimize_chunk: optimize hot update chunk
DEBUG mako::generate::optimize_chunk: optimize chunk
DEBUG mako::generate::optimize_chunk: optimize options: CodeSplittingAdvancedOptions { min_size: 20000, groups: [OptimizeChunkGroup { name: "vendors", name_suffix: None, allow_chunks: Async, min_chunks: 1, min_size: 20000, max_size: 5000000, min_module_size: None, priority: -10, test: Some(Regex("[/\\\\]node_modules[/\\\\]")) }, OptimizeChunkGroup { name: "common", name_suffix: None, allow_chunks: Async, min_chunks: 2, min_size: 1, max_size: 5000000, min_module_size: None, priority: -20, test: None }] }
DEBUG mako::generate::transform: >> mark async in 0ms
DEBUG mako::generate::transform: >> transform modules in 0ms
DEBUG mako::generate: 11217514592350292768 not equals 8208733874001833294
DEBUG mako::generate:   - generate hmr chunk: 5ms
DEBUG mako::generate: generate(hmr) done in 4715ms
DEBUG mako::generate:   - group chunks: 4282ms
DEBUG mako::generate:   - optimize chunks: 415ms
DEBUG mako::generate:   - transform modules: 1ms
DEBUG mako::generate:   - calculate hash: 11ms
DEBUG mako::generate:   - next full hash: 11217514592350292768
DEBUG mako::dev: hot update chunks generated, next_full_hash: Ok((11217514592350292768, 13176523377635441660, 1959008785285148892))
DEBUG mako::dev: hash info, next: 11217514592350292768, last: 8208733874001833294, is_equal: false
DEBUG mako::dev: full rebuild...
DEBUG mako::generate: generate(hmr-fullbuild)
DEBUG mako::generate: ast to code and write
DEBUG mako::generate: ast to code and write
DEBUG mako::generate: write assets
DEBUG mako::generate: generate(hmr-fullbuild) done in 263ms
DEBUG mako::generate:   - generate chunks: 178ms
DEBUG mako::generate:   - ast to code and write: 30ms
DEBUG mako::generate:   - write assets: 1ms
DEBUG mako::dev: full rebuild...done
Full rebuilt in 4981ms
DEBUG mako::dev: receiver count: 1
DEBUG mako::dev: send message to clients
DEBUG mako::dev::watch: ✓ watch in 5ms
DEBUG mako::dev::watch: ✓ refresh watch in 5ms
DEBUG mako::dev: watch paths detected: ["/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx"]
DEBUG mako::dev: checking update status...
Checking...
DEBUG mako::dev::update: update: [("/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx", Modify)]
DEBUG mako::dev::update: checking added...
DEBUG mako::dev::update: checking added...done, has_added:false
DEBUG mako::dev::update: filtering paths...
DEBUG mako::dev::update:   > /home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx is filtered
DEBUG mako::dev::update: filtering paths...done
DEBUG mako::dev::update: remove: []
DEBUG mako::dev::update: after build_by_remove
DEBUG mako::dev::update:   > removed_module_ids: {}
DEBUG mako::dev::update:   > affected_module_ids: {} (these will be added to modified
DEBUG mako::dev::update: modify: ["/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx"]
DEBUG mako::dev::update: build by modify: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" start
DEBUG mako::build::load: load: File { path: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx", relative_path: "src/pages/handle/menus/authRuleManager/index.tsx", extname: "tsx", content: None, is_under_node_modules: false, is_css_modules: false, is_virtual: false, is_entry: false, pathname: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx", search: "", params: [], fragment: None }
DEBUG mako::build::parse: parse js: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "react-refresh"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "react/jsx-dev-runtime"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/layout/ListPage"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./config"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/hooks/useRequestWithParams"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/pro/Table"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "antd"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./components/FormDrawer"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "custom-icons"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/services/evaluation/authentication"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/pro/SearchForm"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/components/pro/Form"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./components/EditorDrawer"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "./util"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/constants/columnConfig"
DEBUG mako::resolve: parent: "/home/abc/demo-project/src/pages/handle/menus/test-module", source: "@/constants"
DEBUG mako::dev::update:   > missing deps: {}
DEBUG mako::build::parse: parse js: "virtual:external_react"
DEBUG mako::dev::update: build by modify: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" end
DEBUG mako::dev::update: after build_by_modify
DEBUG mako::dev::update:   > modified_module_ids: {ModuleId { id: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" }}
DEBUG mako::dev::update:   > add_paths: [] (these will be added to added)
DEBUG mako::dev::update: add: []
DEBUG mako::dev::update: update_result: UpdateResult { added: {}, removed: {}, modified: {ModuleId { id: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" }}, dep_changed: {ModuleId { id: "/home/abc/demo-project/src/pages/handle/menus/test-module/index.tsx" }} }
DEBUG mako::dev: has_missing_deps: false
DEBUG mako::dev: checking update status... done
DEBUG mako::dev: update status is ok, is_updated: true
DEBUG mako::generate: generate_hot_update_chunks start
DEBUG mako::generate: hot-update:generate
DEBUG mako::generate::group_chunk: group_hot_update_chunk
DEBUG mako::generate::group_chunk: group_chunk
DEBUG mako::generate::group_chunk: entries: [ModuleId { id: "/home/abc/test-project/src/.umi/umi.ts?hmr" }]
DEBUG mako::generate::optimize_chunk: optimize hot update chunk
DEBUG mako::generate::optimize_chunk: optimize chunk
DEBUG mako::generate::optimize_chunk: optimize options: CodeSplittingAdvancedOptions { min_size: 20000, groups: [OptimizeChunkGroup { name: "vendors", name_suffix: None, allow_chunks: Async, min_chunks: 1, min_size: 20000, max_size: 5000000, min_module_size: None, priority: -10, test: Some(Regex("[/\\\\]node_modules[/\\\\]")) }, OptimizeChunkGroup { name: "common", name_suffix: None, allow_chunks: Async, min_chunks: 2, min_size: 1, max_size: 5000000, min_module_size: None, priority: -20, test: None }] }
DEBUG mako::generate::transform: >> mark async in 0ms
DEBUG mako::generate::transform: >> transform modules in 1ms
DEBUG mako::generate: 11217514592350292768 equals 11217514592350292768
DEBUG mako::dev: hot update chunks generated, next_full_hash: Ok((11217514592350292768, 5947293896276182812, 13176523377635441660))
DEBUG mako::dev: hash info, next: 11217514592350292768, last: 11217514592350292768, is_equal: true
DEBUG mako::dev: hash equals, will not do full rebuild
DEBUG mako::dev::watch: ✓ watch in 4ms
DEBUG mako::dev::watch: ✓ refresh watch in 4ms

React版本 17.0.2，umi 4.3.12，@umijs/bundler-mako 0.8.0

**Comment by ShotHeadman** [comment]
另外修改代码时，偶尔会出现以下的情况，需要重新启动一遍
![image](https://github.com/user-attachments/assets/2675766a-f647-4dc8-bea0-8ebd50d52e35)

这个项目里有循环引用，不知道跟这个有没有关系

**Comment by ShotHeadman** [comment]
在使用 0.8.3 版本后，Full rebuilt 时间大概在300ms左右，应该没有这个问题了
