### ISSUE TITLE
FEATURE : Support chainWebpack like option

### ISSUE THREAD

**Issue by SquirrelDeveloper** [umijs/mako#1497]
Hi,
This project seems awesome, however, I can't use it because my current UmiJS Max configuration uses
```typescript
  chainWebpack(memo: any) {
    memo.plugin('monaco-editor').use(MonacoEditorWebpackPlugin, []);
    return memo;
  },
```
Ans this feature is not yet supported

**Comment by stormslowly** [comment]
if you just use monaco-editor plugin in chainWebpack, you can reference to this example https://github.com/umijs/mako/blob/master/examples/with-antd/src/pages/monaco-editor.tsx
using `@monaco-editor/react` instead

**Comment by SquirrelDeveloper** [comment]
Removing the webpackchain option is giving me another error and warning with Umi Max :
```
  Mako bundler does not support the following options:
  - theme.[object value]
```
configuration:
``` typescript
theme: {
    'root-entry-name': 'variable',
    token: {
      colorBgSpotlight: '#1d222e',
    },
    components: {
      Modal: {
        contentBg: '#1d222e',
        headerBg: '#1d222e',
      },
    },
  },
```

And another un-related error:
```
 fatal - Error: Cannot find module '@umijs/mako-linux-arm64-musl'

```

**Comment by stormslowly** [comment]
```txt
 fatal - Error: Cannot find module '@umijs/mako-linux-arm64-musl'
```
i will add this target soon

**Comment by sorrycc** [comment]
linux-arm64-musl is supported.
