### ISSUE TITLE
使用Create React App 创建的项目。index.html 中存在%PUBLIC_URL% 如何替换

### ISSUE THREAD

**Issue by nalanwuyou** [umijs/mako#1507]
使用Create React App 创建的项目。index.html 中存在%PUBLIC_URL% 如何替换

**Comment by nalanwuyou** [comment]
> 给个复现步骤？其 `%PUBLIC_URL%` 的作用是什么？
`nvm use 18.20.4  `
`npx create-react-app my-app --template typescript `
`cd  my-app`
`npm i @umijs/mako -D`
`sed -i 's/"build": "react-scripts build"/"build": "mako build --mode production"/' package.json`
`npm run build`
pubilc 文件夹的 index.html下的 %PUBLIC_URL% 在 编译后的 dist/index.html 中还是存在

**Comment by stormslowly** [comment]
目前无法在 CRA 创建的项目中直接使用 mako，建议
1. 直接使用 `npm create mako`, 
2. 或者 umi 的模板项目， 然后开启 mako
