### ISSUE TITLE
[RFC] 输出stats.json、externals支持函数、可修改output.filename

### ISSUE THREAD

**Issue by flgame** [umijs/mako#1512]
最近尝试将umi4项目切换至mako编译，速度飞快，但是之前有些umi插件无法使用，主要有：
1. 无法输出stats.json，我们用来上报编译时长、文件大小、依赖分析等数据
2. externals不支持函数，原来忽略antd 样式文件的代码无效
如：https://www.webpackjs.com/configuration/externals/#function
```js
const antdStyle = /^antd\/.*(\/style|\.css|\.less|\.sass|\.scss)/;
const antdTheme = ({ request }: any, callback: any) => {
  if (antdStyle.test(request)) {
    return callback(null, '{}');
  }
  return callback();
};
```
4. 无法修改output.filename，我们想在hash后面添加_cache，让nginx设置强缓存
```js
const addCacheAddon = (filename) => {
  const extIndex = filename.lastIndexOf(']');
  const chars = filename.split('');
  chars.splice(extIndex + 1, 0, '._cache_');
  return chars.join('');
};
```

请问umi4切换到mako后可以通过什么方式实现呢？

**Comment by xusd320** [comment]
stats 信息现在是通过 generate_end hook 传过来的，可以参考这个改动 https://github.com/umijs/mako/commit/7ceb690bc9568b38708e47eed875387bff17c805#diff-2072e7ddf5e73de8a41bad66fe3581e5ab254090d6df8acfe610041d80acc923

**Comment by xusd320** [comment]
external 可以支持正则的高级配置，不确定能否满足你的需求 https://github.com/umijs/mako/blob/f9fd15ea2f1acb8262d050a54279ac4440f6cb0b/e2e/fixtures/config.externals/mako.config.json#L30

**Comment by Wu-kung** [comment]
> stats 信息现在是通过 generate_end hook 传过来的，可以参考这个改动 [7ceb690#diff-2072e7ddf5e73de8a41bad66fe3581e5ab254090d6df8acfe610041d80acc923](https://github.com/umijs/mako/commit/7ceb690bc9568b38708e47eed875387bff17c805#diff-2072e7ddf5e73de8a41bad66fe3581e5ab254090d6df8acfe610041d80acc923)

stats.json 数据目前还不完整，云谦老师说还需要在 rust 层补全。

**Comment by xusd320** [comment]
问题1: 确认下版本，0.7.9 版本 generate_end 就已经传人 stats 信息了 https://github.com/umijs/mako/blob/master/CHANGELOG.md#079

**Comment by flgame** [comment]
> external 可以支持正则的高级配置，不确定能否满足你的需求
> 
> https://github.com/umijs/mako/blob/f9fd15ea2f1acb8262d050a54279ac4440f6cb0b/e2e/fixtures/config.externals/mako.config.json#L30

按示例配置了，antd的external编译会报错：`config error: data did not match any variant of untagged enum ExternalConfig`
配置如下：
```json
{
  "externals": {
    "antd": {
      "root: "antd",
      "subpath": {
        "exclude": ["style"]
      }
    }
  }
}
```
