### ISSUE TITLE
自定义插件，有大佬开发过没

### ISSUE THREAD

**Issue by wangsanshao** [umijs/mako#1517]
目前公司内部需要将代码在进行一次babel编译，想到是否可以用自定义插件解决这个问题

**Comment by xiaohuoni** [comment]
[mako-project.zip](https://github.com/user-attachments/files/16743017/mako-project.zip)
插件还在修改方案，最终可能会变动，现有的插件用法，给你个参考

**Comment by wangsanshao** [comment]
感谢，我参考一下这个
