### ISSUE TITLE
bug: Page Exception caused by codeSplitting

### ISSUE THREAD

**Issue by withwyf** [umijs/mako#1519]
环境 umijs/max@4.13.12，约定路由

配置codeSplitting 为 granular或者advanced时，编译成功，但访问页面控制台报错 **“Uncaught TypeError： Cannot read property ‘call’ of undefined at runtime_entry.js”** execOptions.factory 不存在

移除codeSplitting配置时页面恢复正常

**Comment by xusd320** [comment]
Need html plugin in umi https://github.com/umijs/umi/pull/12629

**Comment by stormslowly** [comment]
https://github.com/umijs/umi/pull/12629  is merged and published
