### ISSUE TITLE
[Feature] Release mako as a rust library on crates.io

### ISSUE THREAD

**Issue by Ivanmatthew** [umijs/mako#1522]
Currently, the only way to install mako is through the npm registry.

I would like to be able to utilize mako’s bundler capabilities within rust projects too.

Use cases:
- Rust toolchains with TypeScript/JavaScript bundling as a part of their process.
- Rust native tools wanting to extend their functionality with an already production ready bundler.

I’d like to know if this is possible.
Thanks in advance!

**Comment by stormslowly** [comment]
@Ivanmatthew  
could plz try use `mako = { "https://github.com/umijs/mako.git", branch ="master" }`  in cargo file first.

**Comment by Ivanmatthew** [comment]
> @Ivanmatthew could plz try use `mako = { "https://github.com/umijs/mako.git", branch ="master" }` in cargo file first.

This works, however using this option makes you unable to publish the package to crates, as it does not allow packages with dependencies that are not published themselves.

**Comment by sorrycc** [comment]
Sorry for the late reply, mako is not designed to be a library, so we won't do it for now.
