### ISSUE TITLE
[RFC] Consider upgrading the rust toolchain

### ISSUE THREAD

**Issue by shulaoda** [umijs/mako#1528]
This RFC proposes the consideration of upgrading the Rust toolchain to a more recent version.

**Comment by chenrui333** [comment]
+1

**Comment by stormslowly** [comment]
we have to follow swc's toolchain config

**Comment by shulaoda** [comment]
@stormslowly It seems that `SWC` updated rust toolchain to `nightly-2024-07-21` last month.
