### ISSUE TITLE
Cannot find module '@umijs/mako-win32-x64-msvc'

### ISSUE THREAD

**Issue by HawtinZeng** [umijs/mako#1532]
运行 dumi build，报错：
![image](https://github.com/user-attachments/assets/031e150c-35ea-4f68-965d-90f97abcb9d7)

**Comment by haccoco99999** [comment]
![image](https://github.com/user-attachments/assets/853e87bb-16fa-48ab-9e64-d699a81670e5)

**Comment by xiaohuoni** [comment]
https://github.com/umijs/mako/issues/1343
