### ISSUE TITLE
无法解析三方依赖包的web worker

### ISSUE THREAD

**Issue by UnicornZhang** [umijs/mako#1546]
当我使用三方依赖时，此依赖使用web worker，此时会无法解析三方依赖构建的worker路径
<img width="655" alt="image" src="https://github.com/user-attachments/assets/0abd584e-a416-47c5-8261-83de90c7ad4b">
这里有一个最小复现场景：
npm包test-lib：
使用rollup构建，目录结构为
![image](https://github.com/user-attachments/assets/914a781d-8862-4b3e-a119-98bbc79a4750)
index.ts :
![image](https://github.com/user-attachments/assets/c5319f73-78ef-4426-892a-048bb5983793)
worker.ts:
![image](https://github.com/user-attachments/assets/7d97f7e1-1124-4355-aba5-0f13bf6aef45)
rollup.config.js
![image](https://github.com/user-attachments/assets/5ab02f66-4d46-4e14-9bc9-38dc31da200f)
dist:
![image](https://github.com/user-attachments/assets/84073508-33b7-4114-9956-2b731006320d)

测试项目，基于umi max,在home界面引入test-lib
<img width="667" alt="image" src="https://github.com/user-attachments/assets/392c4c1a-5fb5-4730-8fee-1093b8e5bd62">
未开启mako,可构建成功，功能完整
![image](https://github.com/user-attachments/assets/022976c1-f4b4-4469-b179-ec590559a582)
开启mako，无法成功构建
mako配置：
<img width="342" alt="image" src="https://github.com/user-attachments/assets/d83a911b-4979-4fed-a1e9-fe3dfee75567">
错误信息：
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/cbecb1e2-3e25-442f-b852-14c5f9ba4bfd">

@umijs/max:4.3.17

**Comment by UnicornZhang** [comment]
补充：发现worker文件被构建成html结构，导致无法解析
![image](https://github.com/user-attachments/assets/9facbaa6-e86b-44df-9a39-2b8bf55cbf85)

**Comment by xusd320** [comment]
new Worker 应该加上相对路径前缀, 否则会被当成 npm 包解析。估计 rollup 把这个前缀删掉了。
```js
new Worker(new URL('./worker', import.meta.url))
```

**Comment by xusd320** [comment]
Ref: https://docs.rs/oxc_resolver/1.7.0/oxc_resolver/struct.ResolveOptions.html#structfield.prefer_relative
