### ISSUE TITLE
umi配置mako后报js错误 _ is not defined

### ISSUE THREAD

**Issue by lianbuzi** [umijs/mako#1548]
getDictionary(_, RouteToDictionary); 方法调用_为占位符，去掉config 里的配置 mako：{}就好了

**Comment by stormslowly** [comment]
请提给一个完整的最小复现

**Comment by stormslowly** [comment]
估计和 https://github.com/umijs/mako/issues/1549 相关，你看下你的 define 配置，是否定义了  `_`

**Comment by stormslowly** [comment]
你的 `_` 定义是怎么来的，是 define 配置还是额外的插件？
