### ISSUE TITLE
[Bug]: modules cancatenation causes hash instability

### ISSUE THREAD

**Issue by xusd320** [umijs/mako#1562]
Build examples/with-umi twice, compare entry chunk:
<img width="1763" alt="image" src="https://github.com/user-attachments/assets/440dd044-7ee5-4a7a-988d-fa13f23b639f">

**Comment by stormslowly** [comment]
We should compare the compiled  js with non-minify first, those files should be no difference between different builds

**Comment by xusd320** [comment]
> We should compare the compiled js with non-minify first, those files should be no difference between different builds

The only difference happens here.
<img width="1759" alt="image" src="https://github.com/user-attachments/assets/fc811106-4d74-4889-b139-fe0f10436cee">

**Comment by xusd320** [comment]
@stormslowly module concatenation change the codes orders when build redux-sage. 
Disable module concatenation, the hash will be stable.
<img width="874" alt="image" src="https://github.com/user-attachments/assets/4d91a82f-f64b-4092-a58b-8670a61433e3">

**Comment by stormslowly** [comment]
oh, my bad

**Comment by stormslowly** [comment]
close by https://github.com/umijs/mako/pull/1564
