### ISSUE TITLE
npm版本依赖未推送的版本

### ISSUE THREAD

**Issue by xianyunyh** [umijs/mako#1569]
![image](https://github.com/user-attachments/assets/7554e803-9a60-4789-902f-deec00405321)

[mako-linux-arm64-musl](https://www.npmjs.com/package/@umijs/mako-linux-arm64-musl?activeTab=versions)
Hi, 刚CI打包一直报错 **Couldn't find any versions for "@umijs/mako-linux-arm64-musl" that matches "0.8.8"**
我查看github的release，发现10分钟前打了[ `v0.8.8`](https://github.com/umijs/mako/releases/tag/v0.8.8)，但是未推送到npm,是否可以先推送npm后，再修改依赖的版本信息 [package.json](https://github.com/umijs/mako/blob/master/packages/mako/package.json#L76)

**Comment by sevenTiny** [comment]
same issue, please help to push the last version of package @umijs/mako-linux-arm64-musl@0.8.8

**Comment by xianyunyh** [comment]
@sevenTiny 
我在package.json中的resolutions字段中加入 "@umijs/mako": "0.8.7"先临时解决了CI环境下的打包报错
![image](https://github.com/user-attachments/assets/9a217a51-aac2-4f40-840c-9cb26e31d0b9)

**Comment by sevenTiny** [comment]
thanks @xianyunyh

**Comment by stormslowly** [comment]
@xianyunyh  删掉  resolutions 吧，我已经改了 latest tag ， 一会会补发这个包

**Comment by stormslowly** [comment]
![image](https://github.com/user-attachments/assets/73a897c2-2de3-454a-8232-f253c011854c)

sorry for that
