### ISSUE TITLE
使用mako后，日期全变成英文的了

### ISSUE THREAD

**Issue by lsy934127847** [umijs/mako#1573]
使用mfsu
![image](https://github.com/user-attachments/assets/0e5d3837-bc73-4228-b8c0-9b05a979fbc3)

使用 mako
![image](https://github.com/user-attachments/assets/692e3c71-05eb-4854-b39e-27ed02ab41fd)

**Comment by stormslowly** [comment]
麻烦提供一个最小复现 可能是某个 locale 配置没有同步到 mako

**Comment by lsy934127847** [comment]
@ant-design/pro-table 2.26有问题。

**Comment by lsy934127847** [comment]
从 @ant-design/pro-components 导出没有问题， 从 @ant-design/pro-table 导出就变成英文的了。

**Comment by sorrycc** [comment]
可能是多实例了，从 @ant-design/pro-table import 用的时候有两个 pro-components 吧。

**Comment by lsy934127847** [comment]
怎么解决， 智能修改成从  pro-components 导？

**Comment by sorrycc** [comment]
1、不用 mako 关 mfsu 会有问题吗？
2、给「我们可操作」的复现步骤

**Comment by lsy934127847** [comment]
把问题关了，demo项目没复现出来





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chencheng (云谦) ***@***.***&gt;
发送时间: 2024年9月9日 14:31
收件人: umijs/mako ***@***.***&gt;
抄送: lsy934127847 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [umijs/mako] 使用mako后，日期全变成英文的了 (Issue #1573)





 
1、不用 mako 关 mfsu 会有问题吗？
 2、给「我们可操作」的复现步骤
