### ISSUE TITLE
[Bug] windows下umi 项目开启mako后 Invalid Unicode escape sequence

### ISSUE THREAD

**Issue by liuwenzhuang** [umijs/mako#1580]
![image](https://github.com/user-attachments/assets/9167cc5a-bdc5-4d30-8229-2f37c875cc86)

umi 版本：4.3.20
mako版本：0.8.11

**Comment by PeachScript** [comment]
看起来是 `\u` 触发 unicode 转义了，cc @sorrycc

**Comment by gaoxianglyx** [comment]
现在windows上依然报这个错误，由预计支持的时间吗
