### ISSUE TITLE
插件 generateEnd 的 args 参数变更 is_first_compile 变更成 isFirstCompile 

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/mako#1599]
从 mako@0.8.2 升级到 mako@0.8.11
generateEnd 的 args 参数变更is_first_compile 变更成 isFirstCompile 
没有查到记录，不知道是设计变更还是异常。
![image](https://github.com/user-attachments/assets/04ab54c8-95f5-4386-9111-ae7ed5ce45a6)

https://github.com/umijs/umi-plugin-mako/pull/12/files#diff-1a8ddf0627abe771bddbb6fcd316e5cc23cd3bcd2265b982fa5095e6d77c546fR88

**Comment by xusd320** [comment]
之前的版本有问题.. 正确的应该是 isFirstCompile
