### ISSUE TITLE
umi3版本是否可以支持使用mako

### ISSUE THREAD

**Issue by yangxianpei** [umijs/mako#1603]
有些老项目比较庞大,不好升级到umi4 , 现在build和热更新都很慢

**Comment by Jinbao1001** [comment]
https://makojs.dev/docs/getting-started#bundle-with-umi

**Comment by yangxianpei** [comment]
<img width="281" alt="企业微信截图_17268139851976" src="https://github.com/user-attachments/assets/ca534dda-a8bc-4f53-a184-0975f4fb83ec">
less文件里面的图片 引用的是 public下地址报错 怎么解决呀
