### ISSUE TITLE
在浏览器查看源文件数量太多，导致浏览器卡顿，无法正常查看源代码调试

### ISSUE THREAD

**Issue by ByYogi** [umijs/mako#1614]
## 影响
某个文件报错，点击定位文件的链接会导致浏览器检查功能卡顿
![image](https://github.com/user-attachments/assets/0c8b7a77-4eb0-48de-89ac-60958771bfe7)

![image](https://github.com/user-attachments/assets/fa1b3675-60c7-4130-8c3d-bfd66f0d2d11)

**Comment by stormslowly** [comment]
window 上模块 id 处理的问题，目前暂时无法配置部分文件忽略，可关掉 devtool 先等等我们处理好 window 的 bug。
```
{ devtool: false}
```

已经帮你召唤神龙了

**Comment by ByYogi** [comment]
> { devtool: false}

这个配置也没用。等你们修复

**Comment by echoyl** [comment]
直接爆炸
