### ISSUE TITLE
windows环境中 umiMax下 使用Mako运行不起来

### ISSUE THREAD

**Issue by PikachuGits** [umijs/mako#1643]
What happens?

通过 pnpm dlx create-umi@latest 命令创建的新项目
配置mako: {},
![config0](https://github.com/user-attachments/assets/f2d3c930-4681-4976-b932-8938316c2234)

运行 pnpm run dev 后会在20% 终止,并且没有任何报错信息
![Snipaste_2024-10-16_10-51-50](https://github.com/user-attachments/assets/a7af91fc-e5d7-4996-9eb0-66b1bf64b9b8)

umi版本v4.3.26

**Comment by zuorichongxian** [comment]
切换到4.3.24版本可用
