### ISSUE TITLE
umi-max生产模式怎么使用，build后不显示源码，关闭sourcemap

### ISSUE THREAD

**Issue by xu756** [umijs/mako#1658]
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/7caf98c2-2cc9-46b9-a5b4-f0b11f66665d">

**Comment by xu756** [comment]
<img width="817" alt="image" src="https://github.com/user-attachments/assets/3c33a666-d3a6-4321-b46b-54b2cedf58a0">
我展示使用两个文件配置，根据官方文档看到可以配置mode 但 umi 似乎并没有 mako.mode选项

**Comment by sorrycc** [comment]
没理解，你的问题是啥？
