### ISSUE TITLE
React.lazy 引用第三方包报错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/mako#1665]
<img width="330" alt="image" src="https://github.com/user-attachments/assets/91b43fa7-6846-478a-a702-53b1cee0cd06">
<img width="544" alt="image" src="https://github.com/user-attachments/assets/ed2e23f9-8473-4813-a23a-704dfd23f652">
我自定义了一个插件注入到umi的配置中，使用cdn的方式引用，当我关闭mako时是可以正常运行的，开启mako时，程序运行提示无法找到插件。在开启mako时，我尝试使用React.lazy引用本地路径的文件，发现也可以正常运行，但引用我的cdn第三方插件就会报错

_Originally posted by @gank-forme in https://github.com/umijs/umi-plugin-mako/issues/14#issuecomment-2437207858_

**Comment by PeachScript** [comment]
Mako 暂不支持 MF，所以解析不到，支持后应该也需要 `mibMF` 的插件适配

**Comment by xiaohuoni** [comment]
@gank-forme cc
