### ISSUE TITLE
[Bug] EnvReplacer 在 Typescript Declare 环境下失效

### ISSUE THREAD

**Issue by Lemonnnnnnnnnnn** [umijs/mako#1673]
## 版本
- umi: 4.3.6
- mako: 0.9.3

## 问题

umi.define 与 typescript declare 合用时，报错：_ is not defined

## 最简复现

.umirc.ts :

```ts 
import { defineConfig } from 'umi';

export default defineConfig({
    define: { 
        foo:1
    },
    mako:{}
});
```

pages/index.tsx

```ts
declare var foo: string;

export default function HomePage() {
  return (
    <div>
      {foo}
    </div>
  );
}
```

## 期望

页面显示 1

## 相关 issue

https://github.com/umijs/mako/issues/1549

**Comment by stormslowly** [comment]
@Lemonnnnnnnnnnn  thanks a lot
