### ISSUE TITLE
终端能否提供一个类似vite的快捷键操作

### ISSUE THREAD

**Issue by thinkasany** [umijs/mako#1674]
监听 h 出现 帮助面板，然后出现其他的快捷键。

有时候open in browser / clear console / show server url  确实很实用

![image](https://github.com/user-attachments/assets/c34ac1bc-aa29-4b7f-b543-944bb2b59b78)

![image](https://github.com/user-attachments/assets/97e3997c-da35-4343-a97f-51c0b7090b55)

**Comment by sorrycc** [comment]
如果要做，也应该在框架里做。放构建器里做不合适，构建器应只提供构建的原子能力。

**Comment by thinkasany** [comment]
佬的意思是说 放到 umi 这种框架里面去吗，但是如果只用了 mako，并不是 umi 搭建的而是 create react app or next 创建的呢。

但是像 vite 这种，使用 vite 构建的生态直接都能使用了，会很便捷吧，就算不用 某固定框架。写 element-plus、vitest、vitepress这些都可以。 就是确实 mako 执行久了 No changes Checking... 会变得特别特别长，如果忘记域名也挺麻烦，长了想整理也不是很方便，可能就需要重启。

![image](https://github.com/user-attachments/assets/cd9758ff-0355-4800-8067-df3f661ed0e1)

https://github.com/vitejs/vite/blob/1aa434e8017012bf0939b2ff1a3a66b4bd12b76d/packages/vite/src/node/shortcuts.ts#L16

![image](https://github.com/user-attachments/assets/40d560ca-26a5-454c-b55a-bfde8fe467ab)
