### ISSUE TITLE
dev环境下运行编译less报错

### ISSUE THREAD

**Issue by wjaxian** [umijs/mako#1675]
# 环境
umi: 3.5.41
umi-plugin-mako: 0.0.12
antd: ~3.26.20
# 报错截图
<img width="2468" alt="mako-less" src="https://github.com/user-attachments/assets/29378a27-dacc-4105-a1f2-5eebd313fefb">

**Comment by stormslowly** [comment]
@xiaohuoni 帮忙看一眼？

**Comment by xiaohuoni** [comment]
antd: ~3.26.20 ！
@wjaxian 给一个复现（我不知道 antd@3 怎么用！）
