### ISSUE TITLE
[QA]: how to fix `Error watching files: Too many open files (os error 24)`

### ISSUE THREAD

**Issue by DYC-zhanglin** [umijs/mako#1683]
![image](https://github.com/user-attachments/assets/6378aa4f-bfb3-4b1b-a25b-434939c99fc9)

在 https://github.com/tachybase/tachybase 项目中，我们原本 umi 使用的场景没有那么复杂，所以期望能平滑切换到 mako，实际上 build 的过程很顺利，但是开发过程遇到了这个问题，而且不知道怎么解决这个问题。

In the https://github.com/tachybase/tachybase project, our original use of umi wasn't very complex, so we expected a smooth transition to mako. The build process actually went smoothly, but we encountered this issue during development and haven't figured out how to resolve it.

复现方式
Steps to reproduce
```bash
git clone https://github.com/tachybase/tachybase.git
cd tachybase
git checkout feat/migrate-to-mako
pnpm install
pnpm dev --client
```

**Comment by DYC-zhanglin** [comment]
umi@4.3.31
mako@0.9.5

**Comment by Jinbao1001** [comment]
The lockfile is broken?
```
ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-YuKoXDAhBYxY7SfOKxHBDoSyENFeW5VvIIQp2TGQuit8gpK6MnWaQelBKxso72DoxTZfZdcP3W90LqpSkgPzLQ==","tarball":"https://registry.npmjs.org/validate-npm-package-name/-/validate-npm-package-name-5.0.0.tgz"} from the store.
```

**Comment by DYC-zhanglin** [comment]
The lockfile appears to be all good on my side. 
<img width="711" alt="image" src="https://github.com/user-attachments/assets/d67f9859-9230-43dd-b21d-946a4315429b">
By the way, pnpm's version is 9.12.2

**Comment by Jinbao1001** [comment]
定位到问题了, 晚点修复下. 不过我本地跑步起来你们项目, 到时候麻烦你验证下哦 @DYC-zhanglin

**Comment by DYC-zhanglin** [comment]
> 定位到问题了, 晚点修复下. 不过我本地跑不起来你们项目, 到时候麻烦你验证下哦 @DYC-zhanglin

好的，没问题，辛苦了
