### ISSUE TITLE
css global 中存在逗号时，构建报错

### ISSUE THREAD

**Issue by hualigushi** [umijs/mako#1695]
<img width="521" alt="截屏2024-11-18 17 45 46" src="https://github.com/user-attachments/assets/35a129c6-dcf8-40bd-b48b-caddd943e60f">
<img width="835" alt="截屏2024-11-18 17 46 12" src="https://github.com/user-attachments/assets/afe60140-49ce-4a6c-84d2-83aafe118615">

问题：css global 中存在逗号时，构建会报错
预期：不报错
复现仓库：https://github.com/hualigushi/mako-style, src/Table

**Comment by Jinbao1001** [comment]
已知问题, 先这样解决:
- :global(.editable-table, .editable-fixed-right) {
+ :global(.editable-table) :global(.editable-fixed-right) {
  color: red;
}
