### ISSUE TITLE
三方库不存在的导出，mako 没有报错

### ISSUE THREAD

**Issue by hualigushi** [umijs/mako#1697]
<img width="865" alt="截屏2024-11-19 13 56 20" src="https://github.com/user-attachments/assets/9d4dbcdd-1ac7-4b51-a630-c4415c53c34e">
复现仓库：https://github.com/hualigushi/mako-monaco/tree/feature/mako-valtio

预期：开启 mako 后，报错

**Comment by Jinbao1001** [comment]
close with #1709 
```
// mako config
{
    experimental: {
        importsCheck: true
    }
}
```
docs will be supplemented later.
